Implement method inlining
Firmwehr/gentle pull request #146
Opened 2022-01-22 09:06 UTC by SirYwell

This implements method inlining. The current heuristics are somewhat randomly chosen, we might want to do further investigations for good thresholds here and there.

2022-01-26 22:38 UTC, I-Al-Istannen requested changes

2022-01-26 22:38 UTC, I-Al-Istannen commented on src/main/java/com/github/firmwehr/gentle/firm/optimization/MethodInliningOptimization.java
> +	// TODO move into GentleBindings once merged
They are merged already?

2022-01-27 00:08 UTC, chrisliebaer commented on src/main/java/com/github/firmwehr/gentle/firm/optimization/MethodInliningOptimization.java
> +	private static final Logger LOGGER = new Logger(MethodInliningOptimization.class, Logger.LogLevel.DEBUG);
Probably want to disable debug?

2022-01-27 00:08 UTC, chrisliebaer commented on src/main/java/com/github/firmwehr/gentle/firm/optimization/UnusedParameterOptimization.java
> +	private static final Logger LOGGER = new Logger(UnusedParameterOptimization.class, Logger.LogLevel.DEBUG);
Same here I guess

2022-01-27 02:48 UTC, chrisliebaer approved these changes

2022-01-27 10:46 UTC, I-Al-Istannen approved these changes

2022-01-27 10:48 UTC, merged