Add README.md
Firmwehr/gentle pull request #156
Opened 2022-01-27 06:20 UTC by chrisliebaer

2022-03-01 11:40 UTC, intrigus-lgtm approved these changes

2022-03-01 13:15 UTC, libaurea requested changes
Slight nagging at the wording. Consistent wrapping would be nice (80 or 120).

2022-03-01 13:15 UTC, libaurea commented on README.md
> +* no static variables, `public static void main(String[])` is only static method (and kept to stay mostly compatible
is the only static method and is kept to remain compatible with Java

2022-06-04 22:06 UTC, intrigus-lgtm commented on README.md
> +Flammenwehrfer is our cross-repository test bot, runing all tests from our
```suggestion
Flammenwehrfer is our cross-repository test bot, running all tests from our
```

2022-06-04 22:06 UTC, intrigus-lgtm commented on README.md
> +This isn't wrong, but as you might have notices by now we are *far* from sane.
```suggestion
This isn't wrong, but as you might have noticed by now we are *far* from sane.
```

2022-06-05 08:23 UTC, Garmelon approved these changes

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +  and building an abstract syntax tree
```suggestion
  that builds an abstract syntax tree
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +  with e.g. type information and ensuring programs are semantically valid
```suggestion
- a semantic analysis and conversion step that ensures the program is
  semantically valid and attributes the AST with type information
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +- a backend step lowering the libFirm IR to our own Ikea-IR
```suggestion
- a backend step lowering the libFirm IR to our own Ikea IR
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +libFirm offers a C99 frontend (`cparser`) and can output optimized assembly for
```suggestion
[SSA form](https://en.wikipedia.org/wiki/Static_single_assignment_form).
LibFirm offers a C99 frontend (`cparser`) and can output optimized assembly for
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +insertion of Phis to build up a proper SSA structure and dominance to properly
```suggestion
insertion of phis to build up a proper SSA structure and dominance to properly
```
Nicht sicher

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +libFirm is written in C and must therefore be called using JNI - the Java
```suggestion
LibFirm is written in C and must therefore be called using JNI - the Java
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +Gentle supports every feature MiniJava has to offer, but you will have to live
```suggestion
Gentle supports every feature MiniJava has to offer, meaning you will have to live
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +compiler producing the fastest (and correct of course!) binaries.
```suggestion
compiler producing the fastest correct binaries.
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +how compilers work and why they do(n't do) certain things.
```suggestion
how compilers work and why they (don't) do certain things.
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +analysis tools, resulting in a quite robust and stable compiler.
```suggestion
analysis tools, resulting in quite a robust and stable compiler.
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +github issues depending on how well their compiler coped with new tests.
```suggestion
other teams' GitHub issues depending on how well their compiler coped with new tests.
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +re-implementation of the classic AsciiQuarium as well as a fully-functional
```suggestion
re-implementation of the classic asciiquarium as well as a fully-functional
```
consistency

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +wrote an annotation processor parsing Ascii-Art program graphs and emitting
```suggestion
wrote an annotation processor parsing ascii art program graphs and emitting
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +continued to produce bugs crashing our compiler, the compiler of other groups
```suggestion
continued to produce bugs crashing our compiler, the compilers of other groups
```

2022-06-05 08:23 UTC, Garmelon commented on README.md
> +gentle is able to compile *Mini-Java*. Mini-Java is a subset of Java (technically it contains programs which would be
Gentle ist noch klein geschrieben?

2022-06-05 08:48 UTC, chrisliebaer commented on README.md
> +gentle is able to compile *Mini-Java*. Mini-Java is a subset of Java (technically it contains programs which would be
Ich dachte wir würden ihn überall klein schreiben, hatte nicht gesehen, dass er überall groß geschrieben wurden.

2022-06-05 09:04 UTC, Garmelon commented on README.md
> +gentle is able to compile *Mini-Java*. Mini-Java is a subset of Java (technically it contains programs which would be
Am Satzsanfang wäre das schon sinnvoll, ansonsten kann gentle auch gerne klein sein

2022-06-05 11:27 UTC, I-Al-Istannen approved these changes

2022-06-05 20:30 UTC, libaurea requested changes

2022-06-05 20:30 UTC, libaurea commented on README.md
> +It completly elides polymorphism, for a start, but also simpler things like for loops:
```suggestion
invalid in Java due to some edge cases.
The language has been purposefully modified to reduce the scope of supported
language features while maintaining all essential control primitives.
It completely elides polymorphism, for a start, but also simpler things like for loops:
```

2022-06-05 20:35 UTC, pavelzw approved these changes

2022-06-05 20:43 UTC, intrigus-lgtm approved these changes

2022-06-05 20:45 UTC, intrigus approved these changes

2022-06-05 20:46 UTC, pavelzw commented
LGTM!

2022-06-05 20:56 UTC, SirYwell approved these changes
🥸

2022-06-06 15:01 UTC, merged